"""new coulum model address

Revision ID: 9fc5ab8f69dc
Revises: 
Create Date: 2022-08-03 23:46:42.390497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc5ab8f69dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
